name: Point to Pull Request Template

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave: |
            Hello world ! :wave: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
